import sys

SYSTEM = sys.platform
MACOS = 'darwin'
WINDOWS = 'win32'
LINUX = 'linux'

PIXEL_FACTOR = 2

WIDTH = 55 // PIXEL_FACTOR #256 // 2
HEIGHT = 55 // PIXEL_FACTOR #180 // 2

CURRENT_DEVICE = None

IS_DRAWING = False

ENABLE_PRINTING = True

NUMBER_OF_PIXEL_TRIALS = 5
TRIAL_TIMEOUT = 0.5 #: seconds