FONTS: list = []
FONTS_DICT: dict = {}
PROGRESS_BAR_VALUE: int = 0

PREVIEW_REFRESH_TIME: int = 100
FIND_DEVICE_TIME: int = 1000

DEFAULT_MAINWINDOW_WIDTH: int = 600
DEFAULT_MAINWINDOW_HEIGHT: int = 400

DEFAULT_FONTSIZE: int = 20

IGNORE_FONTS: bool = True
